### ISSUE TITLE
BUG: does not handle own CancelledError on client.close()

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [robertmrk/aiocometd#7]
1. great project, thank you

2. in v 0.4.5: BUG: does not handle own CancelledError on client.close():
```
2020-01-19 08:54:02 INFO aiocometd.client:287  close                   Closing client...
2020-01-19 08:54:02 ERRO      asyncio:199  exception_reactor       Exception in callback <bound method TransportBase._connect_done of <aiocometd.transports.websocket.WebSocketTransport object at 0x7f9e62e90fa0>>
handle: <Handle TransportBase._connect_done>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/lib/python3.8/site-packages/aiocometd/transports/base.py", line 541, in _connect_done
    result: Union[JsonObject, Exception] = future.result()
asyncio.exceptions.CancelledError
2020-01-19 08:54:02 ERRO      asyncio:199  exception_reactor       Exception in callback <bound method WebSocketTransport._receive_done of <aiocometd.transports.websocket.WebSocketTransport object at 0x7f9e62e90fa0>>
handle: <Handle WebSocketTransport._receive_done>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/lib/python3.8/site-packages/aiocometd/transports/websocket.py", line 261, in _receive_done
    result = future.result()
asyncio.exceptions.CancelledError
2020-01-19 08:54:03 INFO aiocometd.client:298  close                   Client closed.
```

3. in `aiocometd/transports/base.py`:
https://github.com/robertmrk/aiocometd/blob/0.4.5/aiocometd/transports/base.py#L541

4. in `aiocometd/transports/websocket.py`:
https://github.com/robertmrk/aiocometd/blob/0.4.5/aiocometd/transports/websocket.py#L261

5. in both cases these are internal tasks, which are both created and canceled by `aiocometd`,
and they both propagate own `aiocometd` initiated `CancelledError` to the event loop
exception handler

**Comment by Graeme22** [comment]
Same issue here. Is this project still maintained?

**Comment by Andrei-Pozolotin** [comment]
1. works in this fork:
https://github.com/random-python/x_aiocometd
2. activate with `pip` via `requirements.txt`:
```config
### aiocometd == 0.4.5 ### disable
aiocometd @ git+https://github.com/random-python/x_aiocometd@develop ### enalbe ###

```

**Comment by Graeme22** [comment]
> 1. works in this fork:
>    https://github.com/random-python/x_aiocometd
> 2. activate with `pip` via `requirements.txt`:
> 
> ```
> ### aiocometd == 0.4.5 ### disable
> git+https://github.com/random-python/x_aiocometd@develop ### enalbe ###
> ```

~~This is great! Could you create a release so that if it's used as a dependency it can point to a specific version instead of the `develop` branch?~~

Made my own!
